### ISSUE TITLE
Compiling `elixir_v8` fails with log `make: *** No rule to make target 'v8'`

### ISSUE THREAD

**Issue by piglovesyou** [strange/erlang_v8#4]
Hi. I was trying to compile `elixir_v8` that depends on your `erlang_v8` and it fails with the log below.

After I changed `make v8` to `make` in `elixir_v8/deps/erlang_v8/rebar.confg`, it works fine. I'm new to erlang/elixir and not sure, but it seems some of make targets is missing/wrongly specified in your Makefile. How is it?

```
[pig@localhost elixir_v8]$ mix test
(...)

===> Compiling erlang_v8
make: *** No rule to make target 'v8'.  Stop.
===> Hook for compile failed!

** (Mix) Could not compile dependency :erlang_v8, "/home/pig/.mix/rebar3 bare compile --paths "/home/pig/git/elixir_v8/_build/test/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile erlang_v8", update it with "mix deps.update erlang_v8" or clean it with "mix deps.clean erlang_v8"
```

**Comment by strange** [comment]
I haven't used rebar in a while. I'll fix it. Good catch!

**Comment by piglovesyou** [comment]
Thanks.
